/** Steps 6-7: push the branch and open (or reuse) an MR/PR describing the workflow that produced it. */

import { push } from '../git/commit.js';
import { runStep, note } from '../ui/steps.js';
import type { ForgeClient } from '../forge/types.js';
import type { CapturedIntent, MergeRequest } from '../types.js';

/** Renders the MR/PR description as: Intent, Summary, per-file changes, Risk, Test Scenarios. */
export function buildDescription(intent: CapturedIntent, agentName: string): string {
  const fileChanges = intent.fileChanges.map((f) => `- \`${f.file}\`: ${f.summary}`).join('\n');
  const testScenarios = intent.testScenarios.map((s) => `- ${s}`).join('\n');
  const risk = intent.risk.charAt(0).toUpperCase() + intent.risk.slice(1);

  return (
    `**Intent:** ${intent.intent}\n\n` +
    `**Summary:** ${intent.summary}\n\n` +
    `**File changes:**\n${fileChanges}\n\n` +
    `**Risk:** ${risk} — ${intent.riskReason}\n\n` +
    `**Test Scenarios:**\n${testScenarios}\n\n` +
    '---\n' +
    `Generated by \`pipeline-worker\`: intent captured via **${agentName}**, ` +
    'build/lint/test passed locally before this MR was opened. ' +
    'If the pipeline fails, pipeline-worker will attempt automated fixes (up to the configured retry cap) before escalating here.'
  );
}

export async function openMergeRequest(
  forge: ForgeClient,
  worktreePath: string,
  branch: string,
  targetBranch: string,
  intent: CapturedIntent,
  agentName: string,
): Promise<MergeRequest> {
  await runStep(9, '⬆', 'Pushing your branch', `push ${branch} to origin`, () => push(worktreePath, 'origin', branch));

  const existing = await forge.findExistingMr(branch);
  if (existing) {
    note(`reusing existing merge request ${existing.webUrl}`);
    return existing;
  }

  const description = buildDescription(intent, agentName);

  const mr = await runStep(
    10,
    '🔀',
    'Opening merge request',
    `target branch: ${targetBranch}`,
    () => forge.createMergeRequest({ sourceBranch: branch, targetBranch, title: intent.commitMessage, description }),
  );
  note(mr.webUrl);
  return mr;
}
