/** Steps 'push' and 'mr': push the branch and open (or reuse) an MR/PR describing the workflow that produced it. */

import { push } from '../git/commit.js';
import { runStep, skipStep, addDynamicStep, note, noteRisk } from '../ui/steps.js';
import type { ForgeClient } from '../forge/types.js';
import type { CapturedIntent, CheckResult, MergeMethod, MergeRequest } from '../types.js';

/**
 * ✅/❌ per check, mirroring the pass/fail glyphs cli.ts prints for the same
 * stage (see ui/steps.ts). An empty list means the `resume` branch-adoption
 * path is refreshing an existing MR/PR's description without re-running
 * local checks (see adoptBranch.ts) — that's not a check that failed to run,
 * so it gets its own placeholder rather than an empty section.
 */
function formatChecks(checks: CheckResult[]): string {
  if (checks.length === 0) return '_Not run locally for this update — see the CI pipeline below._';
  return checks.map((c) => `- ${c.ok ? '✅' : '❌'} ${c.name} (${(c.durationMs / 1000).toFixed(1)}s)`).join('\n');
}

/** Renders the MR/PR description as: Intent, Summary, per-file changes, Risk, Checks, Test Scenarios. */
export function buildDescription(intent: CapturedIntent, agentName: string, checks: CheckResult[]): string {
  const fileChanges = intent.fileChanges.map((f) => `- \`${f.file}\`: ${f.summary}`).join('\n');
  const testScenarios = intent.testScenarios.map((s) => `- ${s}`).join('\n');
  const risk = intent.risk.charAt(0).toUpperCase() + intent.risk.slice(1);

  return (
    `**Intent:** ${intent.intent}\n\n` +
    `**Summary:** ${intent.summary}\n\n` +
    `**File changes:**\n${fileChanges}\n\n` +
    `**Risk:** ${risk} — ${intent.riskReason}\n\n` +
    `**Checks:**\n${formatChecks(checks)}\n\n` +
    `**Test Scenarios:**\n${testScenarios}\n\n` +
    '---\n' +
    `Generated by \`pipeline-worker\`: intent captured via **${agentName}**. ` +
    'If the pipeline fails, pipeline-worker will attempt automated fixes (up to the configured retry cap) before escalating here.'
  );
}

/**
 * A follow-up run's block, appended to (never replacing) the MR/PR's existing
 * description: the reviewer's own text, the original intent, and every
 * earlier follow-up all stay readable above it, so the description reads as
 * the change log of the review conversation. Same per-file breakdown as
 * buildDescription's, since that file-wise documentation is the point of
 * appending at all.
 */
export function buildFollowUpSection(intent: CapturedIntent, agentName: string, checks: CheckResult[]): string {
  const fileChanges = intent.fileChanges.map((f) => `- \`${f.file}\`: ${f.summary}`).join('\n');
  const risk = intent.risk.charAt(0).toUpperCase() + intent.risk.slice(1);

  return (
    `### 🔁 Follow-up: ${intent.commitMessage}\n\n` +
    `**Summary:** ${intent.summary}\n\n` +
    `**File changes:**\n${fileChanges}\n\n` +
    `**Risk:** ${risk} — ${intent.riskReason}\n\n` +
    `**Checks:**\n${formatChecks(checks)}\n\n` +
    `_Appended by \`pipeline-worker\` (intent via **${agentName}**) when this commit was added to the open MR/PR._`
  );
}

/** Joins a follow-up section onto an existing description with a horizontal rule, tolerating an empty/whitespace-only description. */
export function appendSection(existingDescription: string, section: string): string {
  const existing = existingDescription.trimEnd();
  return existing.length === 0 ? section : `${existing}\n\n---\n\n${section}`;
}

/**
 * The "reviewer asked for a change" path: this run's commit belongs on the
 * branch of an already-open MR/PR, not on a new branch of its own. Pushes the
 * worktree's HEAD onto that branch and appends the file-wise breakdown to the
 * description.
 *
 * Deliberately does not touch auto-merge or the title: both may have been
 * changed by a human since the MR/PR was opened, and a follow-up commit is no
 * reason to overrule them.
 *
 * Returns the id of whatever pipeline the forge reports as latest for this
 * MR/PR *before* the push below — the caller (ensureMergeRequest) threads it
 * into watchPipeline as the id to treat as stale. GitLab/GitHub both take a
 * beat to register a new pipeline after a push; without this, the CI-watch
 * loop's very first poll can see that pre-existing (already terminal)
 * pipeline as "latest" and mistake it for the one this push triggers,
 * reporting a stale pass/fail instead of waiting for the real one.
 * `undefined` when the MR/PR has no pipeline at all yet.
 */
export async function appendToMergeRequest(
  forge: ForgeClient,
  worktreePath: string,
  mr: MergeRequest,
  intent: CapturedIntent,
  agentName: string,
  checks: CheckResult[],
): Promise<number | undefined> {
  const pipelinesBeforePush = await forge.getMrPipelines(mr.iid);
  const priorPipelineId = pipelinesBeforePush[0]?.id;

  await runStep('push', `push this commit onto ${mr.sourceBranch}, the branch of ${mr.webUrl}`, () => push(worktreePath, 'origin', mr.sourceBranch));

  await runStep('mr', `appending the file-wise breakdown to ${mr.webUrl}'s description`, async () => {
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const desc = await forge.getMrDescription(mr.iid);
        const newDescription = appendSection(desc.text, buildFollowUpSection(intent, agentName, checks));
        await forge.updateMrDescription(mr.iid, newDescription, desc.version);
        return;
      } catch (error) {
        if (error instanceof Error && error.message.includes('ConflictError') && attempt < 2) {
          continue;
        }
        throw error;
      }
    }
  });
  note(mr.webUrl);
  return priorPipelineId;
}

/**
 * Best-effort: repo settings (GitHub's "Allow auto-merge" toggle unset, no
 * required checks configured) or GitLab's async merge-status computation can
 * both cause the forge to reject this — never let that fail an otherwise
 * fully-successful run. The fallback is simply what happens today: the
 * developer merges manually once CI is green.
 */
async function maybeEnableAutoMerge(forge: ForgeClient, mr: MergeRequest, autoMergeOnGreen: boolean, mergeMethod: MergeMethod): Promise<void> {
  addDynamicStep('mr', 'mr/auto-merge', 'auto-merge');
  if (!autoMergeOnGreen) {
    skipStep('mr/auto-merge', 'config.autoMergeOnGreen is disabled');
    return;
  }
  try {
    await runStep('mr/auto-merge', `merge method: ${mergeMethod}`, () => forge.enableAutoMerge(mr.iid, mergeMethod));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    noteRisk('medium', `could not enable auto-merge (${message}) — merge manually once CI is green`);
  }
}

export async function openMergeRequest(
  forge: ForgeClient,
  worktreePath: string,
  branch: string,
  targetBranch: string,
  intent: CapturedIntent,
  agentName: string,
  checks: CheckResult[],
  autoMergeOnGreen = false,
  mergeMethod: MergeMethod = 'squash',
): Promise<MergeRequest> {
  await runStep('push', `push ${branch} to origin`, () => push(worktreePath, 'origin', branch));

  const existing = await forge.findExistingMr(branch);
  if (existing) {
    skipStep('mr', `an MR/PR already exists for this branch — reusing ${existing.webUrl} instead of opening a new one`);
    // Deliberately does not (re-)enable auto-merge here: a resumed run reusing
    // an existing MR/PR must not silently turn on something a human may have
    // turned off since it was opened.
    return existing;
  }

  const description = buildDescription(intent, agentName, checks);

  const mr = await runStep(
    'mr',
    `target branch: ${targetBranch}`,
    () => forge.createMergeRequest({ sourceBranch: branch, targetBranch, title: intent.commitMessage, description }),
  );
  note(mr.webUrl);

  await maybeEnableAutoMerge(forge, mr, autoMergeOnGreen, mergeMethod);

  return mr;
}
