/** Stages 10-11: push the branch and open (or reuse) an MR/PR describing the workflow that produced it. */

import { push } from '../git/commit.js';
import { runStep, skipStep, note, noteRisk } from '../ui/steps.js';
import type { ForgeClient } from '../forge/types.js';
import type { CapturedIntent, CheckResult, MergeMethod, MergeRequest } from '../types.js';

/**
 * ✅/❌ per check, mirroring the pass/fail glyphs cli.ts prints for the same
 * stage (see ui/steps.ts). An empty list means the `resume` branch-adoption
 * path is refreshing an existing MR/PR's description without re-running
 * local checks (see adoptBranch.ts) — that's not a check that failed to run,
 * so it gets its own placeholder rather than an empty section.
 */
function formatChecks(checks: CheckResult[]): string {
  if (checks.length === 0) return '_Not run locally for this update — see the CI pipeline below._';
  return checks.map((c) => `- ${c.ok ? '✅' : '❌'} ${c.name} (${(c.durationMs / 1000).toFixed(1)}s)`).join('\n');
}

/** Renders the MR/PR description as: Intent, Summary, per-file changes, Risk, Checks, Test Scenarios. */
export function buildDescription(intent: CapturedIntent, agentName: string, checks: CheckResult[]): string {
  const fileChanges = intent.fileChanges.map((f) => `- \`${f.file}\`: ${f.summary}`).join('\n');
  const testScenarios = intent.testScenarios.map((s) => `- ${s}`).join('\n');
  const risk = intent.risk.charAt(0).toUpperCase() + intent.risk.slice(1);

  return (
    `**Intent:** ${intent.intent}\n\n` +
    `**Summary:** ${intent.summary}\n\n` +
    `**File changes:**\n${fileChanges}\n\n` +
    `**Risk:** ${risk} — ${intent.riskReason}\n\n` +
    `**Checks:**\n${formatChecks(checks)}\n\n` +
    `**Test Scenarios:**\n${testScenarios}\n\n` +
    '---\n' +
    `Generated by \`pipeline-worker\`: intent captured via **${agentName}**. ` +
    'If the pipeline fails, pipeline-worker will attempt automated fixes (up to the configured retry cap) before escalating here.'
  );
}

/**
 * Best-effort: repo settings (GitHub's "Allow auto-merge" toggle unset, no
 * required checks configured) or GitLab's async merge-status computation can
 * both cause the forge to reject this — never let that fail an otherwise
 * fully-successful run. The fallback is simply what happens today: the
 * developer merges manually once CI is green.
 */
async function maybeEnableAutoMerge(forge: ForgeClient, mr: MergeRequest, autoMergeOnGreen: boolean, mergeMethod: MergeMethod): Promise<void> {
  if (!autoMergeOnGreen) {
    skipStep('11.1', '🔀', 'Enabling auto-merge on green', 'config.autoMergeOnGreen is disabled');
    return;
  }
  try {
    await runStep('11.1', '🔀', 'Enabling auto-merge on green', `merge method: ${mergeMethod}`, () => forge.enableAutoMerge(mr.iid, mergeMethod));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    noteRisk('medium', `could not enable auto-merge (${message}) — merge manually once CI is green`);
  }
}

export async function openMergeRequest(
  forge: ForgeClient,
  worktreePath: string,
  branch: string,
  targetBranch: string,
  intent: CapturedIntent,
  agentName: string,
  checks: CheckResult[],
  autoMergeOnGreen = false,
  mergeMethod: MergeMethod = 'squash',
): Promise<MergeRequest> {
  await runStep(10, '⬆', 'Pushing your branch', `push ${branch} to origin`, () => push(worktreePath, 'origin', branch));

  const existing = await forge.findExistingMr(branch);
  if (existing) {
    skipStep(11, '🔀', 'Opening merge request', `an MR/PR already exists for this branch — reusing ${existing.webUrl} instead of opening a new one`);
    // Deliberately does not (re-)enable auto-merge here: a resumed run reusing
    // an existing MR/PR must not silently turn on something a human may have
    // turned off since it was opened.
    return existing;
  }

  const description = buildDescription(intent, agentName, checks);

  const mr = await runStep(
    11,
    '🔀',
    'Opening merge request',
    `target branch: ${targetBranch}`,
    () => forge.createMergeRequest({ sourceBranch: branch, targetBranch, title: intent.commitMessage, description }),
  );
  note(mr.webUrl);

  await maybeEnableAutoMerge(forge, mr, autoMergeOnGreen, mergeMethod);

  return mr;
}
